export interface SelectValuesType {
    code: string;
    label: string;
    suggested?: boolean;
}

export const paisesISOAlpha3: SelectValuesType[]  = [
    {label:"Afganistán",code:"afg"},
    {label:"Albania",code:"alb"},
    {label:"Alemania",code:"deu"},
    {label:"Andorra",code:"and"},
    {label:"Angola",code:"ago"},
    {label:"Antigua y Barbuda",code:"atg"},
    {label:"Arabia Saudita",code:"sau"},
    {label:"Argelia",code:"dza"},
    {label:"Argentina",code:"arg"},
    {label:"Armenia",code:"arm"},
    {label:"Australia",code:"aus"},
    {label:"Austria",code:"aut"},
    {label:"Azerbaiyán",code:"aze"},
    {label:"Bahamas",code:"bhs"},
    {label:"Bangladés",code:"bgd"},
    {label:"Barbados",code:"brb"},
    {label:"Baréin",code:"bhr"},
    {label:"Bélgica",code:"bel"},
    {label:"Belice",code:"blz"},
    {label:"Benín",code:"ben"},
    {label:"Bielorrusia",code:"blr"},
    {label:"Bolivia",code:"bol"},
    {label:"Bosnia y Herzegovina",code:"bih"},
    {label:"Botsuana",code:"bwa"},
    {label:"Brasil",code:"bra"},
    {label:"Brunéi",code:"brn"},
    {label:"Bulgaria",code:"bgr"},
    {label:"Burkina Faso",code:"bfa"},
    {label:"Burundi",code:"bdi"},
    {label:"Bután",code:"btn"},
    {label:"Cabo Verde",code:"cpv"},
    {label:"Camboya",code:"khm"},
    {label:"Camerún",code:"cmr"},
    {label:"Canadá",code:"can"},
    {label:"Catar",code:"qat"},
    {label:"Chad",code:"tcd"},
    {label:"Chile",code:"chl"},
    {label:"China",code:"chn"},
    {label:"Chipre",code:"cyp"},
    {label:"Colombia",code:"col"},
    {label:"Comoras",code:"com"},
    {label:"Corea del Norte",code:"prk"},
    {label:"Corea del Sur",code:"kor"},
    {label:"Costa de Marfil",code:"civ"},
    {label:"Costa Rica",code:"cri"},
    {label:"Croacia",code:"hrv"},
    {label:"Cuba",code:"cub"},
    {label:"Dinamarca",code:"dnk"},
    {label:"Dominica",code:"dma"},
    {label:"Ecuador",code:"ecu"},
    {label:"Egipto",code:"egy"},
    {label:"El Salvador",code:"slv"},
    {label:"Emiratos Árabes Unidos",code:"are"},
    {label:"Eritrea",code:"eri"},
    {label:"Eslovaquia",code:"svk"},
    {label:"Eslovenia",code:"svn"},
    {label:"España",code:"esp"},
    {label:"Estados Unidos",code:"usa", suggested: true},
    {label:"Estonia",code:"est"},
    {label:"Etiopía",code:"eth"},
    {label:"Filipinas",code:"phl"},
    {label:"Finlandia",code:"fin"},
    {label:"Fiyi",code:"fji"},
    {label:"Francia",code:"fra"},
    {label:"Gabón",code:"gab"},
    {label:"Gambia",code:"gmb"},
    {label:"Georgia",code:"geo"},
    {label:"Ghana",code:"gha"},
    {label:"Granada",code:"grd"},
    {label:"Grecia",code:"grc"},
    {label:"Guatemala",code:"gtm"},
    {label:"Guinea",code:"gin"},
    {label:"Guinea-Bisáu",code:"gnb"},
    {label:"Guinea Ecuatorial",code:"gnq"},
    {label:"Guyana",code:"guy"},
    {label:"Haití",code:"hti"},
    {label:"Honduras",code:"hnd"},
    {label:"Hungría",code:"hun"},
    {label:"India",code:"ind"},
    {label:"Indonesia",code:"idn"},
    {label:"Irak",code:"irq"},
    {label:"Irán",code:"irn"},
    {label:"Irlanda",code:"irl"},
    {label:"Islandia",code:"isl"},
    {label:"Islas Marshall",code:"mhl"},
    {label:"Islas Salomón",code:"slb"},
    {label:"Israel",code:"isr"},
    {label:"Italia",code:"ita"},
    {label:"Jamaica",code:"jam"},
    {label:"Japón",code:"jpn"},
    {label:"Jordania",code:"jor"},
    {label:"Kazajistán",code:"kaz"},
    {label:"Kenia",code:"ken"},
    {label:"Kirguistán",code:"kgz"},
    {label:"Kiribati",code:"kir"},
    {label:"Kuwait",code:"kwt"},
    {label:"Laos",code:"lao"},
    {label:"Lesoto",code:"lso"},
    {label:"Letonia",code:"lva"},
    {label:"Líbano",code:"lbn"},
    {label:"Liberia",code:"lbr"},
    {label:"Libia",code:"lby"},
    {label:"Liechtenstein",code:"lie"},
    {label:"Lituania",code:"ltu"},
    {label:"Luxemburgo",code:"lux"},
    {label:"Macedonia del Norte",code:"mkd"},
    {label:"Madagascar",code:"mdg"},
    {label:"Malasia",code:"mys"},
    {label:"Malaui",code:"mwi"},
    {label:"Maldivas",code:"mdv"},
    {label:"Malí",code:"mli"},
    {label:"Malta",code:"mlt"},
    {label:"Marruecos",code:"mar"},
    {label:"Mauricio",code:"mus"},
    {label:"Mauritania",code:"mrt"},
    {label:"México",code:"mex",suggested: true},
    {label:"Micronesia",code:"fsm"},
    {label:"Moldavia",code:"mda"},
    {label:"Mónaco",code:"mco"},
    {label:"Mongolia",code:"mng"},
    {label:"Montenegro",code:"mne"},
    {label:"Mozambique",code:"moz"},
    {label:"Birmania",code:"mmr"},
    {label:"Namibia",code:"nam"},
    {label:"Nauru",code:"nru"},
    {label:"Nepal",code:"npl"},
    {label:"Nicaragua",code:"nic"},
    {label:"Niger",code:"ner"},
    {label:"Nigeria",code:"nga"},
    {label:"Noruega",code:"nor"},
    {label:"Nueva Zelanda",code:"nzl"},
    {label:"Omán",code:"omn"},
    {label:"Paises Bajos",code:"nld"},
    {label:"Pakistán",code:"pak"},
    {label:"Palaos",code:"plw"},
    {label:"Panamá",code:"pan"},
    {label:"Papúa Nueva Guinea",code:"png"},
    {label:"Paraguay",code:"pry"},
    {label:"Perú",code:"per"},
    {label:"Polonia",code:"pol"},
    {label:"Portugal",code:"prt"},
    {label:"Reino Unido",code:"gbr"},
    {label:"República Centroafricana",code:"caf"},
    {label:"República Checa",code:"cze"},
    {label:"República del Congo",code:"cog"},
    {label:"República Democrática del Congo",code:"cod"},
    {label:"República Dominicana",code:"dom"},
    {label:"Ruanda",code:"rwa"},
    {label:"Rumania",code:"rou"},
    {label:"Rusia",code:"rus"},
    {label:"Samoa",code:"wsm"},
    {label:"San Cristóbal y Nieves",code:"kna"},
    {label:"San Marino",code:"smr"},
    {label:"San Vicente y las Granadinas",code:"vct"},
    {label:"Santa Lucía",code:"lca"},
    {label:"Santo Tomé y Príncipe",code:"stp"},
    {label:"Senegal",code:"sen"},
    {label:"Serbia",code:"srb"},
    {label:"Seychelles",code:"syc"},
    {label:"Sierra Leona",code:"sle"},
    {label:"Singapur",code:"sgp"},
    {label:"Siria",code:"syr"},
    {label:"Somalia",code:"som"},
    {label:"Sri Lanka",code:"lka"},
    {label:"Suazilandia",code:"swz"},
    {label:"Sudáfrica",code:"zaf"},
    {label:"Sudán",code:"sdn"},
    {label:"Sudán del Sur",code:"ssd"},
    {label:"Suecia",code:"swe"},
    {label:"Suiza",code:"che"},
    {label:"Surinam",code:"sur"},
    {label:"Tailandia",code:"tha"},
    {label:"Tanzania",code:"tza"},
    {label:"Tayikistán",code:"tjk"},
    {label:"Timor Oriental",code:"tls"},
    {label:"Togo",code:"tgo"},
    {label:"Tonga",code:"ton"},
    {label:"Trinidad y Tobago",code:"tto"},
    {label:"Túnez",code:"tun"},
    {label:"Turkmenistán",code:"tkm"},
    {label:"Turquía",code:"tur"},
    {label:"Tuvalu",code:"tuv"},
    {label:"Ucrania",code:"ukr"},
    {label:"Uganda",code:"uga"},
    {label:"Uruguay",code:"ury"},
    {label:"Uzbekistán",code:"uzb"},
    {label:"Vanuatu",code:"vut"},
    {label:"Venezuela",code:"ven"},
    {label:"Vietnam",code:"vnm"},
    {label:"Yemen",code:"yem"},
    {label:"Yibuti",code:"dji"},
    {label:"Zambia",code:"zmb"},
    {label:"Zimbabue",code:"zwe"},
    {label:"Hong Kong",code:"hkg"},
    {label:"Puerto Rico",code:"pri"},
    {label:"Sudafrica",code:"saf"},
    {label:"Taiwan",code:"twn"},
    {label:"URSS",code:"sun"},
    {label:"Holanda",code:"nld"},
    {label:"Checoslovaquia",code:"csk"},
    {label:"Union Sovietica",code:"sun"},
    {label:"Bermudas",code:"bmu"}
    ]